/*
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the ULTRASONIC driver
 *
 * Author: Fady Essam
 */

#include "ultrasonic.h"
#include "icu.h"
#include <avr/io.h>
#include "gpio.h"
#include "util/delay.h"

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

/* declaring variable "g_edgeCount" as static to be used in ultrasonic only*/
static uint8 g_edgeCount = 0;

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/* Description
➢ Initialize the ICU driver as required.
➢ Setup the ICU call back function.
➢ Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void){

	/*initiallize the ICU with prescaler of F_CPU/8 and detect the rising edge*/
	ICU_ConfigType ICU_Configurations = {F_CPU_8,RAISING};

	/* Initialize the ICU driver */
	ICU_init(&ICU_Configurations);

	/* Set the Call back function pointer in the ICU driver */
	ICU_setCallBack(Ultrasonic_edgeProcessing);



	GPIO_setupPinDirection(PORTB_ID,PIN5_ID,PIN_OUTPUT);
}


/* Description
Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void){

	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_LOW);
}

/* Description
Send the trigger pulse by using Ultrasonic_Trigger function.
Start the measurements by the ICU from this moment.
 */

uint16 Ultrasonic_readDistance(void){

	uint16 distance = 0;
	Ultrasonic_Trigger();
	ICU_setEdgeDetectionType(RAISING);
	while (g_edgeCount != 2);
	g_edgeCount = 0;
	/*
	 * after calculations of the distance for 8MHz and prescaler of F_CPU/8
	 * distance = (time*velocity)/2 = = 17000 x (TIMER value) x 1 x 10^-6 cm
	 * = 0.017 x (TIMER value) cm
	 * = (TIMER value) / 58.8 cm
	 * 1 + (TIMER value) / 58 cm
	 */
	distance = 1 + ICU_getInputCaptureValue() /58;

	return distance;
}

/* Description
This is the call back function called by the ICU driver.
This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void){
	/* increment the counter */
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*Clear the timer counter register once again*/
		ICU_clearTimerValue();
		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
}

